
# configuration for client using absolute mouse mode

[core]
include = common/controller.conf
include = common/video-x264.conf
#include = common/audio-opus.conf
include = common/audio-lame.conf

[ga-client]
max-tolerable-video-delay = 0
video-specific[threads] = auto

# comment out the below line if you intended to use s/w renderer
#video-renderer = software

# comment out the below lines for measurement and testing purpose
#save-yuv-image = D:\TEMP\capture.yuv
#save-yuv-image = /tmp/capture.yuv

#max-tolerable-video-delay = 300000

# 클라이언트에서 수신한 YUV 프레임을 하나의 파일로 저장
save-yuv-image = /home/kukhyeon/Desktop/yuv/client.yuv

# 클라이언트에서 수신한 프레임의 타임스탬프 저장
save-yuv-image-timestamp = /home/kukhyeon/Desktop/yuv/client_timestamp.txt

# ⭐ 클라이언트에서 수신된 패킷 크기 로그 저장  
enable-decoding-size-log = 0
save-decoding-size-log = /home/kukhyeon/Desktop/yuv/received_packet_client.txt

# packet loss
save-pktloss-log = /home/kukhyeon/Desktop/yuv/pktloss.log

enable-bandwidth-log = 0

# 윈도우 위치 설정 (픽셀 단위, 기본값: 화면 중앙)
# 좌상단 모서리에 위치시키려면:
# window-x = 0
# window-y = 0
# 특정 위치에 고정하려면:
window-x = 50
window-y = 50

