
# for ga-server-periodic only
# it will capture the entire desktop

[core]
include = common/server-common.conf
include = common/controller.conf
include = common/video-x264.conf
include = common/video-x264-param.conf
include = common/audio-lame.conf

# [ga-server-periodic]
#enable-audio = true
#capture-cursor = true

# comment out the below lines for measurement and testing purpose
#save-yuv-image = /tmp/capture.yuv
#embed-colorcode = 5 80 80

[ga-server-periodic]
enable-audio = false
capture-cursor = true

# ============Select Game===============
#find-window-name = SuperTuxKart
#SUPERHOT
find-window-name = Hollow Knight
#find-window-name = An Amazing Wizard Prologue
#find-window-name = 1024x768.jpg
#find-window-name = Lutris
#find-window-name = Crystal Project Demo
# ======================================

# =========Network Monitoring===========
# UDP 기반 RTT 측정 활성화 (0: 비활성화, 1: 활성화)
enable-udp-rtt = 0

# ICMP 기반 Ping 측정 활성화 (0: 비활성화, 1: 활성화)
enable-icmp-ping = 1
# ======================================


# =========Video-Reconfigure ===========

# Test
enable-reconfigure = 0

# 적응형 비트레이트(ABR) 제어 활성화 (0: 비활성화, 1: 활성화)
# 활성화 시 네트워크 지연 시간에 따라 비트레이트와 FPS가 자동 조절됩니다.
enable-abr = 1
# ⭐ ABR 변경 내역 로그 경로 추가
save-abr-log = /home/kukhyeon/Desktop/yuv/abr_status.txt
# =======================================



# comment out the below lines for measurement and testing purpose#
save-yuv-image = /home/kukhyeon/Desktop/yuv/server.yuv

embed-colorcode = 7 0 0
# ================================================================

save-colorcode-timestamp = /home/kukhyeon/Desktop/yuv/colorcode_timestamp.txt

# ⭐ 서버에서 전송한 프레임 ID 로그 저장
enable-frame-id-log = 1
save-frame-id-timestamp = /home/kukhyeon/Desktop/yuv/frame_id_server.txt

# ⭐ 서버에서 인코딩된 패킷 크기 로그 저장
enable-frame-size-log = 0
save-frame-size-log = /home/kukhyeon/Desktop/yuv/encoded_packet_server.txt

# bw estimator
enable-feedback-log = 1
save-feedback-log = /home/kukhyeon/Desktop/yuv/feedback.txt

# Network RTT
save-rtt-log = /home/kukhyeon/Desktop/yuv/udp_rtt.txt

# transmission calling
enable-fps-log = 0
save-fps-log = /home/kukhyeon/Desktop/yuv/frame_count.txt

save-icmp-log = /home/kukhyeon/Desktop/yuv/ping.txt


